# Generated by Django 5.1.4 on 2025-01-13 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0003_alter_mlmtree_referral_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mlmtree',
            name='valid_position',
        ),
        migrations.AddConstraint(
            model_name='mlmtree',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0), ('position__lte', 5)), name='valid_position'),
        ),
    ]
