# Generated by Django 5.1.4 on 2025-01-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0004_remove_mlmtree_valid_position_mlmtree_valid_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmtree',
            name='commission_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='mlmtree',
            name='turnover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
