# Generated by Django 5.1.4 on 2025-02-16 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0007_scheduledcommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('direct', 'Direct Income'), ('level', 'Level Income'), ('reward', 'Life Time Reward Income'), ('royalty', 'Royalty Company Turnover')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_earned', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='p2pmb.mlmtree')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('star', 'Star Reward'), ('silver', 'Silver Reward'), ('gold', 'Gold Reward'), ('diamond', 'Diamond Reward'), ('titan', 'Titan Reward'), ('conqueron', 'Conqueron Reward'), ('almighty', 'Almighty Reward'), ('relic', 'Relic Reward'), ('commander', 'Commander Reward'), ('immortal', 'Immortal Reward'), ('blue_sapphire', 'The Blue Sapphire Reward')], max_length=20)),
                ('turnover_required', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('months_duration', models.IntegerField()),
                ('achieved_date', models.DateField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='p2pmb.mlmtree')),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_type', models.CharField(choices=[('star', 'Star Club'), ('2_star', '2-Star Club'), ('3_star', '3-Star Club'), ('5_star', '5-Star Club')], max_length=10)),
                ('turnover_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_clubs', to='p2pmb.mlmtree')),
            ],
        ),
    ]
