# Generated by Django 5.1.4 on 2025-02-19 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0009_remove_commission_date_earned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2pmb_commission_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
