# Generated by Django 5.1.4 on 2025-02-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0010_alter_commission_commission_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmtree',
            name='send_direct_income',
            field=models.BooleanField(default=False),
        ),
    ]
