# Generated by Django 5.1.4 on 2025-02-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0011_mlmtree_send_direct_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmtree',
            name='send_level_income',
            field=models.BooleanField(default=False),
        ),
    ]
