# Generated by Django 5.1.4 on 2025-02-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0012_mlmtree_send_level_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcommission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
