# Generated by Django 5.1.4 on 2025-02-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0013_scheduledcommission_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmtree',
            name='is_working_id',
            field=models.BooleanField(default=False),
        ),
    ]
