# Generated by Django 5.1.4 on 2025-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0015_mlmtree_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='applicable_for',
            field=models.CharField(choices=[('super_agency', 'Star Agency'), ('agency', 'Agency'), ('field_agent', 'field_agent'), ('p2pmb', 'p2pmb')], default='p2pmb', max_length=15),
        ),
    ]
