# Generated by Django 5.1.4 on 2025-03-09 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0016_package_applicable_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PMBRoyaltyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('total_turnover', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('calculated_amount_turnover', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('star_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('two_star_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('three_star_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lifetime_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('month', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('eligible_user', models.ManyToManyField(blank=True, related_name='royalty_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
