# Generated by Django 5.1.4 on 2025-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0017_p2pmbroyaltymaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmtree',
            name='show_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
