# Generated by Django 5.1.4 on 2025-03-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0018_mlmtree_show_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='level_type',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down')], max_length=8, null=True),
        ),
    ]
