# Generated by Django 5.1.4 on 2025-03-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0022_alter_coreincomeearned_income_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreincomeearned',
            name='income_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
