# Generated by Django 5.1.4 on 2025-03-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0024_p2pmbroyaltymaster_is_distributed_royaltyearned'),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltyearned',
            name='earned_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
