# Generated by Django 5.1.4 on 2025-06-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0025_royaltyearned_earned_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
