# Generated by Django 5.1.4 on 2025-07-15 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0026_package_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pmbroyaltymaster',
            name='is_five_star_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p2pmbroyaltymaster',
            name='is_star_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p2pmbroyaltymaster',
            name='is_three_star_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p2pmbroyaltymaster',
            name='is_two_star_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledcommission',
            name='commission_type',
            field=models.CharField(default='direct', max_length=50),
        ),
        migrations.CreateModel(
            name='ExtraRewardEarned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('extra_rewar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_reward', to='p2pmb.extrareward')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_reward_earned_user', to='p2pmb.extrareward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
