# Generated by Django 5.1.4 on 2025-07-15 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0027_p2pmbroyaltymaster_is_five_star_distributed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrarewardearned',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_reward_earned_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
