# Generated by Django 5.1.4 on 2025-07-15 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0028_alter_extrarewardearned_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrarewardearned',
            old_name='extra_rewar',
            new_name='extra_reward',
        ),
    ]
