# Generated by Django 5.1.4 on 2025-07-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0030_holdlevelincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdlevelincome',
            name='released_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
