# Generated by Django 5.1.4 on 2025-11-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2pmb', '0032_lapsedamount_roioverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
