# Generated by Django 5.1.4 on 2025-08-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inappnotification',
            name='read_at',
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='read_at_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
