# Generated by Django 5.1.4 on 2025-01-21 14:54

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwarePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', django_ckeditor_5.fields.CKEditor5Field()),
                ('terms_and_conditions', django_ckeditor_5.fields.CKEditor5Field()),
                ('software_version', models.CharField(blank=True, max_length=20, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Software Policy',
                'verbose_name_plural': 'Software Policies',
            },
        ),
    ]
