# Generated by Django 5.1.4 on 2025-01-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_referral_by_alter_profile_verified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldagent',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rewardearned',
            name='company',
        ),
        migrations.RemoveField(
            model_name='incomesource',
            name='company',
        ),
        migrations.RemoveField(
            model_name='fieldagent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fieldagent',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='fieldagent',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='incomesource',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='incomesource',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='rewardearned',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='rewardearned',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rewardearned',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='FieldAgent',
        ),
        migrations.DeleteModel(
            name='IncomeSource',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.DeleteModel(
            name='RewardEarned',
        ),
    ]
