# Generated by Django 5.1.4 on 2025-02-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_agency_profile_is_field_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='other_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
