# Generated by Django 5.1.4 on 2025-02-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_referral_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
