# Generated by Django 5.1.4 on 2025-03-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_changerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
