# Generated by Django 5.1.4 on 2025-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_payment_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonaldocument',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
