# Generated by Django 5.1.4 on 2025-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userpersonaldocument_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
