# Generated by Django 5.1.4 on 2025-04-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_kyc_reprocess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpersonaldocument',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='userpersonaldocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
