# Generated by Django 5.1.4 on 2025-05-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_image_code_alter_userpersonaldocument_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='type',
            field=models.CharField(blank=True, choices=[('register', 'Register'), ('login', 'Login'), ('forgot', 'Forgot'), ('delete', 'Delete'), ('resend', 'Resend')], default='register', max_length=20, null=True),
        ),
    ]
