# Generated by Django 5.1.4 on 2025-05-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_otp_is_verify_otp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('kyc', 'KYC'), ('god', 'GOD'), ('vendor_listing', 'Vendor Listing'), ('accounting', 'Accounting')], max_length=25, null=True),
        ),
    ]
