# Generated by Django 5.1.4 on 2025-06-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
