# Generated by Django 5.1.4 on 2025-06-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_roi_send',
            field=models.BooleanField(default=True),
        ),
    ]
