# Generated by Django 5.1.4 on 2025-06-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_parent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='account_holder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='ifsc_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='new_account_holder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='new_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='new_bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='new_ifsc_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='new_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
