# Generated by Django 5.1.4 on 2025-06-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_changerequest_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='new_bank_address',
            field=models.CharField(default='', max_length=250),
        ),
    ]
