# Generated by Django 5.1.4 on 2025-07-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_changerequest_new_bank_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='beneficiary_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
