# Generated by Django 5.1.4 on 2025-07-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_bankdetails_beneficiary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='upi_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
