# Generated by Django 5.1.4 on 2025-11-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_appversion_deviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonaldocument',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='document_file'),
        ),
        migrations.AlterField(
            model_name='userpersonaldocument',
            name='type',
            field=models.CharField(blank=True, choices=[('pan_card', 'Pan Card'), ('aadhar_front', 'Aadhar Card Front'), ('aadhar_back', 'Aadhar Card Back'), ('passbook', 'Passbook'), ('cancelled_cheque', 'Cancelled Cheque'), ('company_registration', 'Company Registration'), ('shop_image', 'Shop Image'), ('shop_agreement', 'Shop Agreement'), ('kyc_photo', 'KYC Photo'), ('video', 'Video')], max_length=25, null=True),
        ),
    ]
