# Generated by Django 5.1.4 on 2025-01-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('turnover_threshold', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reward_description', models.TextField()),
                ('applicable_for', models.CharField(choices=[('customer', 'Customer'), ('field_agent', 'Field Agent'), ('agency', 'Agency'), ('super_agency', 'Super Agency'), ('p2pmb', 'Person to Person')], default='super_agency', max_length=100)),
            ],
            options={
                'ordering': ['applicable_for'],
            },
        ),
    ]
