# Generated by Django 5.1.4 on 2025-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_rewardmaster_created_by_rewardmaster_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='carousel_type',
            field=models.CharField(blank=True, choices=[('1', 'Carousel 1'), ('2', 'Carousel 2'), ('3', 'Carousel 3'), ('4', 'Carousel 4'), ('5', 'Carousel 5'), ('6', 'Carousel 6'), ('7', 'Carousel 7'), ('8', 'Carousel 8'), ('9', 'Carousel 9'), ('10', 'Carousel 10')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='is_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
