# Generated by Django 5.1.4 on 2025-02-11 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_bannerimage_carousel_type_bannerimage_is_carousel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankDetailsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('bank_address', models.CharField(blank=True, max_length=250, null=True)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('is_applicable_for_super_agency', models.BooleanField(default=False)),
                ('is_applicable_for_agency', models.BooleanField(default=False)),
                ('is_applicable_for_field_agent', models.BooleanField(default=False)),
                ('is_applicable_for_p2pmb', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
