# Generated by Django 5.1.4 on 2025-02-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_companybankdetailsmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardmaster',
            name='gift_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
