# Generated by Django 5.1.4 on 2025-02-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_rewardmaster_gift_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardmaster',
            name='total_paid_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
