# Generated by Django 5.1.4 on 2025-02-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_royaltymaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='royaltymaster',
            name='club_type',
            field=models.CharField(choices=[('star', 'Star Club'), ('2_star', '2-Star Club'), ('3_star', '3-Star Club'), ('5_star', '5-Star Club')], max_length=20),
        ),
    ]
