# Generated by Django 5.1.4 on 2025-02-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_royaltymaster_club_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetailsmaster',
            name='is_applicable_for_customer',
            field=models.BooleanField(default=False),
        ),
    ]
