# Generated by Django 5.1.4 on 2025-03-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualfund',
            name='fund_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('deduct', 'Deduct')], default='deposit', max_length=50),
        ),
    ]
