# Generated by Django 5.1.4 on 2025-07-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0006_alter_userfunctionalityaccesspermission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvestment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
