# Generated by Django 5.1.4 on 2025-01-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('investment', 'Investment'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('send', 'Send'), ('transfer', 'Transfer'), ('reward', 'Reward'), ('commission', 'Commission'), ('refund', 'Refund')], max_length=10),
        ),
    ]
