# Generated by Django 5.1.4 on 2025-02-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('neft', 'NEFT'), ('rtgs', 'RTGS'), ('upi', 'UPI'), ('cards', 'Cards'), ('imps', 'IMPS'), ('wallet', 'Wallet'), ('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('investment', 'Investment'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('send', 'Send'), ('receive', 'Receive'), ('transfer', 'Transfer'), ('reward', 'Reward'), ('commission', 'Commission'), ('refund', 'Refund'), ('rent', 'Rent'), ('interest', 'Interest')], max_length=10),
        ),
    ]
