# Generated by Django 5.1.4 on 2025-03-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_userwallet_p2pmb_royalty_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
