# Generated by Django 5.1.4 on 2025-07-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0007_transaction_tds_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='admin_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
