# Generated by Django 5.1.4 on 2025-01-25 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertybooking_propertyenquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybooking',
            name='booked_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_for_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
