# Generated by Django 5.1.4 on 2025-01-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertybooking_booked_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybooking',
            name='booked_for',
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertybooking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
