# Generated by Django 5.1.4 on 2025-04-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_is_featured_feature_nearbyfacility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential property'), ('commercial', 'Commercial property'), ('industrial', 'Industrial property'), ('agricultural', 'Agricultural property'), ('special', 'Special purpose'), ('co_working', 'Co-working spaces'), ('vacation', 'Vacation rentals'), ('mixed_use', 'Mixed-use properties'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
