# Generated by Django 5.1.4 on 2025-04-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyfacility',
            name='distance',
            field=models.CharField(max_length=150),
        ),
    ]
