# Generated by Django 5.1.4 on 2025-01-13 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_refundpolicy_refund_initiate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundpolicy',
            name='refund_initiate_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
