# Generated by Django 5.1.4 on 2025-01-16 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_refundpolicy_refund_initiate_date'),
        ('master', '0003_rewardmaster_created_by_rewardmaster_date_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardearned',
            name='reward',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.rewardmaster'),
        ),
        migrations.RemoveField(
            model_name='rewardearned',
            name='company',
        ),
        migrations.AddField(
            model_name='rewardearned',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rewardearned',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards_earned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
