# Generated by Django 5.1.4 on 2025-01-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_investment_package_investment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
