# Generated by Django 5.1.4 on 2025-01-26 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_investment_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundpolicy',
            name='refund_initiate_date',
        ),
        migrations.AddField(
            model_name='refundpolicy',
            name='refund_initiate_on',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
