# Generated by Django 5.1.4 on 2025-02-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_remove_refundpolicy_refund_initiate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_guaranteed_type',
            field=models.CharField(blank=True, choices=[('guaranteed_investment', 'Guaranteed Investment'), ('non_guaranteed_investment', 'Non Guaranteed Investment')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rewardearned',
            name='total_month',
            field=models.IntegerField(default=0),
        ),
    ]
