# Generated by Django 5.1.4 on 2025-02-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_investment_investment_guaranteed_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='superagency',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.CharField(choices=[('private_company', 'Private Company'), ('one_person_company', 'One Person Company'), ('public_company', 'Public Company'), ('llp', 'LLP'), ('ngo', 'NGO'), ('enterprise', 'Enterprise')], default='enterprise', max_length=250),
        ),
        migrations.AlterField(
            model_name='superagency',
            name='type',
            field=models.CharField(choices=[('private_company', 'Private Company'), ('one_person_company', 'One Person Company'), ('public_company', 'Public Company'), ('llp', 'LLP'), ('ngo', 'NGO'), ('enterprise', 'Enterprise')], default='enterprise', max_length=250),
        ),
    ]
