# Generated by Django 5.1.4 on 2025-02-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_agency_gst_number_superagency_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='office_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
