# Generated by Django 5.1.4 on 2025-02-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_agency_office_area'),
        ('master', '0005_companybankdetailsmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_city', to='master.city'),
        ),
        migrations.AddField(
            model_name='fieldagent',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_agent_city', to='master.city'),
        ),
        migrations.AddField(
            model_name='superagency',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_agency_city', to='master.city'),
        ),
    ]
