# Generated by Django 5.1.4 on 2025-02-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_agency_city_fieldagent_city_superagency_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='guaranteed_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
