# Generated by Django 5.1.4 on 2025-02-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_investment_guaranteed_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppdaccount',
            name='last_interest_pay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
