# Generated by Django 5.1.4 on 2025-02-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_ppdaccount_last_interest_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardearned',
            name='is_p2p',
            field=models.BooleanField(default=False),
        ),
    ]
