# Generated by Django 5.1.4 on 2025-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_investment_approved_by_investment_approved_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='pay_method',
            field=models.CharField(choices=[('new', 'New'), ('main_wallet', 'Main Wallet'), ('app_wallet', 'App Wallet')], default='new', max_length=20),
        ),
    ]
