# Generated by Django 5.1.4 on 2025-03-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_investment_referral_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='send_direct_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='send_level_income',
            field=models.BooleanField(default=False),
        ),
    ]
