# Generated by Django 5.1.4 on 2025-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_investment_send_direct_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_guaranteed_type',
            field=models.CharField(blank=True, choices=[('full_investment', 'Full Investment'), ('half_investment', 'Half Investment')], max_length=30, null=True),
        ),
    ]
