# Generated by Django 5.1.4 on 2025-03-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0020_alter_investment_investment_guaranteed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_guaranteed_type',
            field=models.CharField(blank=True, choices=[('full_payment', 'Full Payment'), ('part_payment', 'Part Payment')], max_length=30, null=True),
        ),
    ]
