# Generated by Django 5.1.4 on 2025-03-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0021_alter_investment_investment_guaranteed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='pay_method',
            field=models.CharField(choices=[('new', 'New'), ('deduct', 'Deduct'), ('main_wallet', 'Main Wallet'), ('app_wallet', 'App Wallet')], default='new', max_length=20),
        ),
    ]
