# Generated by Django 5.1.4 on 2025-03-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_alter_investment_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_royalty_calculate',
            field=models.BooleanField(default=False),
        ),
    ]
