# Generated by Django 5.1.4 on 2025-03-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_investment_is_royalty_calculate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardearned',
            name='last_payment_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardearned',
            name='total_installment_paid',
            field=models.IntegerField(default=0),
        ),
    ]
