# Generated by Django 5.1.4 on 2025-03-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0024_rewardearned_last_payment_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_interest_send',
            field=models.BooleanField(default=False),
        ),
    ]
