# Generated by Django 5.1.4 on 2025-05-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0026_investmentinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'verbose_name': 'Agency Commission', 'verbose_name_plural': 'Agency Commission'},
        ),
        migrations.AddField(
            model_name='commission',
            name='applicable_for',
            field=models.CharField(choices=[('super_agency', 'Star Agency'), ('agency', 'Agency'), ('field_agent', 'field_agent')], default='super_agency', max_length=15),
        ),
        migrations.AddField(
            model_name='commission',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('direct', 'Direct Income'), ('level', 'Level Income'), ('reward', 'Reward Income'), ('royalty', 'Royalty Company Turnover'), ('rent', 'Rent'), ('revenue_by_agency', 'Revenue By Agency'), ('revenue_by_field_agent', 'Revenue By Field Agent'), ('turnover_commission', 'Turnover Commission'), ('sale_commission', 'Sale Commission'), ('ppd_interest', 'PPD Interest')], max_length=30),
        ),
    ]
