# Generated by Django 5.1.4 on 2025-06-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0028_alter_commission_applicable_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundwithdrawal',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundwithdrawal',
            name='withdrawal_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
