# Generated by Django 5.1.4 on 2025-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0029_fundwithdrawal_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundwithdrawal',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
