# Generated by Django 5.1.4 on 2025-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0030_fundwithdrawal_action_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundwithdrawal',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
