# Generated by Django 5.1.4 on 2025-08-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0032_fundwithdrawal_action_taken_by'),
        ('payment_app', '0009_tdssubmissionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundwithdrawal',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_transaction', to='payment_app.transaction'),
        ),
    ]
