# Generated by Django 5.1.4 on 2025-10-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0033_fundwithdrawal_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='earned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
