# Generated by Django 5.1.4 on 2025-11-10 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0034_commission_earned_at'),
        ('p2pmb', '0032_lapsedamount_roioverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('direct', 'Direct Income'), ('level', 'Level Income'), ('reward', 'Reward Income'), ('royalty', 'Royalty Company Turnover'), ('rent', 'Rent'), ('revenue_by_agency', 'Revenue By Agency'), ('agency_commission', 'Agency Commission'), ('field_agent_commission', 'Field Agent Commission'), ('revenue_by_field_agent', 'Revenue By Field Agent'), ('turnover_commission', 'Turnover Commission'), ('sale_commission', 'Sale Commission'), ('ppd_interest', 'PPD Interest')], max_length=30),
        ),
        migrations.CreateModel(
            name='AgencyPackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('buy_for', models.CharField(choices=[('super_agency', 'Super Agency'), ('agency', 'Agency'), ('field_agent', 'Field Agent'), ('customer', 'Customer'), ('p2pmb', 'Person 2 Person')], max_length=30)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_purchases', to='agency.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('field_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_agent_purchases', to='agency.fieldagent')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='p2pmb.package')),
                ('super_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_agency_purchases', to='agency.superagency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
