# Generated by Django 5.1.4 on 2025-11-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0035_alter_commission_commission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superagency',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
